### ISSUE TITLE
Skill Group context menu is misplaced in resolutions other than 1080p

### ISSUE THREAD

**Issue by SpectralCathe** [PinewoodPip/EpipEncounters#6]
![image](https://github.com/PinewoodPip/EpipEncounters/assets/92652275/66594c10-d2c0-42a7-bf29-a163ff9f3202)

**Comment by PinewoodPip** [comment]
Probably an issue with the positioning logic, since the context menu API is so old it likely uses a janky conversion from cursor pos -> UIObject pos because back then cursor pos could only be fetched at flash level iirc?

**Comment by PinewoodPip** [comment]
Was discussed here https://discord.com/channels/607369048929468456/608788140550914069/1149796814782996521 and fixed some time later; closing.
